/*
consulta para el nivel 3
*/

DEFINE VAR ProductTransactionProducts = NATURALINNERJOIN('mlg_sprint_4 product_transaction', 'mlg_sprint_4 transaction')
       VAR UserTransactionsProducts   = NATURALINNERJOIN(ProductTransactionProducts, 'mlg_sprint_4 user')
       VAR FullSalesTable             = NATURALINNERJOIN(UserTransactionsProducts,   'mlg_sprint_4 product')

EVALUATE
    SELECTCOLUMNS(
        FullSalesTable,
        "product_id",       'mlg_sprint_4 product_transaction'[product_id],
        "user_id",          'mlg_sprint_4 transaction'[user_id],
        "transaction_id",   'mlg_sprint_4 product_transaction'[transaction_id],
        "company_id",       'mlg_sprint_4 transaction'[company_id],
        "Credit Card ID",   'mlg_sprint_4 transaction'[credit_card_id],
        "latitude",         'mlg_sprint_4 transaction'[latitude],
        "longitude",        'mlg_sprint_4 transaction'[longitude],
        "Client Name",      RELATED('mlg_sprint_4 user'[Nombre]),
        "Client City",      RELATED('mlg_sprint_4 user'[city]),
        "Client Country",   RELATED('mlg_sprint_4 user'[country]),
        "Company Name",     RELATED('mlg_sprint_4 company'[company_name]),
        "Company Country",  RELATED('mlg_sprint_4 company'[country]),
        "Product Name",     'mlg_sprint_4 product'[product_name],
        "Product Colour",   'mlg_sprint_4 product'[colour],
        "Product Price",    'mlg_sprint_4 product'[price],
        "transaction_val",  'mlg_sprint_4 transaction'[amount],
        "declined",         'mlg_sprint_4 transaction'[CountableDeclined],
        "transaction_date", 'mlg_sprint_4 transaction'[transaction_ts],
        "transaction_year", 'mlg_sprint_4 transaction'[transaction_year]
    )
    ORDER BY [Client Name]
